name: Build and Test

on:
  push:
    branches: [ main ]

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: "root1234"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    #          --disable_tls1_3=1
    steps:
      - name: Create database
        run: |
          mysql --host=127.0.0.1 --port=3306 --user=root --password="root1234" --execute="CREATE DATABASE IF NOT EXISTS ems;"

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Change directory
        run: cd $GITHUB_WORKSPACE
      - name: List files in directory
        run: ls -al
      - name: List files in project directory
        run: |
          cd $GITHUB_WORKSPACE
          find . -type f

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          architecture: x64
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success

#      - name: Build with Maven
#        run: mvn clean test

      - name: Run Cucumber tests
        run: mvn clean verify

      - name: Archive Cucumber Reports
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: target/cucumber-html-reports/

      - name: Download Cucumber Reports
        uses: actions/download-artifact@v2
        with:
          name: cucumber-report
          path: cucumber-report

      - name: Publish Cucumber Reports
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: cucumber-report/

